name: fluttertest
description: "IbAl — Your cover, the right way."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  get : ^4.6.6
  get_storage: ^2.1.1
  share_plus: ^10.1.3
  go_router: ^14.2.0
  url_launcher: ^6.2.0
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 
   
flutter:

  uses-material-design: true

  assets: 
   - assets/images/
   - .env

flutter_launcher_icons:
 android: true 
 ios: true 
 image_path: "assets/icon/icon.png"
 web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"